export const RENT_CREATE = 'RENT_CREATE'
export const RENT_FETCH_ALL = 'RENT_FETCH_ALL'
export const RENT_UPDATE = 'RENT_UPDATE'
export const RENT_FETCH = 'RENT_FETCH'
export const RENT_DELETE_ALL = 'RENT_DELETE_ALL'
export const RENT_DELETE = 'RENT_DELETE'